// src/utils/constants.js

// Helper function to convert price string to number
const parsePrice = (priceStr) => {
  if (typeof priceStr === 'number') return priceStr;
  return parseInt(priceStr.replace('$', '')) || 0;
};

// Helper function to calculate original price for discounted items
const calculateOriginalPrice = (price, discount) => {
  if (!discount) return null;
  const currentPrice = parsePrice(price);
  const discountPercent = parseInt(discount) / 100;
  return `$${Math.round(currentPrice / (1 - discountPercent))}`;
};

// Featured products
export const featuredProducts = [
  {
    id: 1,
    category: "electronics",
    brand: "oppo",
    img: "/images1/imag6.png",
    discount: "",
    title: "Oppo Find X7 Ultra", 
    price: "$700",
    originalPrice: null,
    rating: 4.5,
    reviewCount: 36,
    inStock: true,
    tags: ["featured", "electronics"],
    isNew: false
  },
  {
    id: 2,
    category: "electronics",
    brand: "dyson", 
    img: "/images1/imag9.png",
    discount: "50%",
    title: "Dyson Airstrait",
    price: "$800",
    originalPrice: "$1600",
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    tags: ["sale", "featured", "electronics", "accessory"],
    isNew: true
  },
  {
    id: 3,
    category: "beauty",
    brand: "olive",
    img: "/images1/image10.png",
    discount: "",
    title: "100% Extra Virgin Olive Oil", 
    price: "$150",
    originalPrice: null,
    rating: 4.2,
    reviewCount: 42,
    inStock: true,
    tags: ["featured", "beauty", "accessory"],
    isNew: false
  },
  {
    id: 4,
    category: "clothing",
    brand: "velomy",
    img: "/images1/imag13.png",
    discount: "50%",
    title: "VELOMY Sweaters",
    price: "$900",
    originalPrice: "$1800",
    rating: 4.3,
    reviewCount: 28,
    inStock: true,
    tags: ["sale", "featured", "clothing"],
    isNew: false
  },
  {
    id: 5,
    category: "electronics",
    brand: "shreeji",
    img: "/images1/imag7.png",
    discount: "",
    title: "SHREEJI FASHION™ Hair Straightener",
    price: "$800",
    originalPrice: null,
    rating: 4.1,
    reviewCount: 31,
    inStock: false,
    tags: ["featured", "electronics", "accessory"],
    isNew: true
  },
  {
    id: 6,
    category: "home",
    brand: "luxury", 
    img: "/images1/imag33.png",
    discount: "",
    title: "Single Sofa Light Luxury",
    price: "$500",
    originalPrice: null,
    rating: 4.6,
    reviewCount: 67,
    inStock: true,
    tags: ["featured", "home"],
    isNew: false
  },
  {
    id: 7,
    category: "beauty",
    brand: "needly",
    img: "/images1/imag16.png",
    discount: "50%",
    title: "Needly Daily Toner",
    price: "$200",
    originalPrice: "$400",
    rating: 4.4,
    reviewCount: 58,
    inStock: true,
    tags: ["sale", "featured", "beauty", "accessory"],
    isNew: true
  },
  {
    id: 8,
    category: "home",
    brand: "wrapping",
    img: "/images1/imag11.png",
    discount: "",
    title: "Wrapping Chair Molded",
    price: "$560",
    originalPrice: null,
    rating: 4.0,
    reviewCount: 24,
    inStock: true,
    tags: ["featured", "home"],
    isNew: false
  },
  {
    id: 9,
    category: "clothing",
    brand: "tall", 
    img: "/images1/imag18.png",
    discount: "50%",
    title: "The Tall Rosedale High-Rise Straight Pant",
    price: "$200",
    originalPrice: "$400",
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    tags: ["sale", "featured", "clothing"],
    isNew: true
  },
  {
    id: 10,
    category: "clothing",
    brand: "darley",
    img: "/images1/imag19.png",
    discount: "50%",
    title: "Small Darley Mulberry Green",
    price: "$200",
    originalPrice: "$400",
    rating: 4.5,
    reviewCount: 36,
    inStock: true,
    tags: ["sale", "featured", "clothing", "accessory"],
    isNew: false
  },
  {
    id: 11,
    category: "electronics",
    brand: "apple",
    img: "/images1/imag20.png",
    discount: "50%",
    title: "Apple AirPods Pro",
    price: "$200",
    originalPrice: "$400",
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    tags: ["sale", "featured", "bestseller", "electronics", "accessory"],
    isNew: false
  },
  {
    id: 12,
    category: "clothing",
    brand: "toteme",
    img: "/images1/imag21.png",
    discount: "50%",
    title: "TOTEME Pleated Pants",
    price: "$200",
    originalPrice: "$400",
    rating: 4.3,
    reviewCount: 47,
    inStock: true,
    tags: ["sale", "featured", "clothing"],
    isNew: true
  }
];

export const newProducts = [
  {
    id: 13,
    category: "home",
    brand: "dedon",
    img: "/images1/imag23.png",
    discount: "50%",
    title: "Dedon Yin Yang Outdoor Double Chaise",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.8,
    reviewCount: 94,
    inStock: true,
    tags: ["sale", "new", "home"],
    isNew: true
  },
  {
    id: 14,
    category: "beauty",
    brand: "looks", 
    img: "/images1/imag4.png",
    discount: "",
    title: "Looks & Meii Natural BB Cream",
    price: "$100",
    originalPrice: null,
    rating: 4.2,
    reviewCount: 52,
    inStock: true,
    tags: ["new", "beauty", "accessory"],
    isNew: true
  },
  {
    id: 15,
    category: "clothing",
    brand: "haut",
    img: "/images1/imag3.png",
    discount: "50%",
    title: "Haut et pantalon décontractés",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.4,
    reviewCount: 38,
    inStock: true,
    tags: ["sale", "new", "clothing"],
    isNew: true
  },
  {
    id: 16,
    category: "beauty",
    brand: "sunscreen",
    img: "/images1/imag30.png",
    discount: "50%",
    title: "Sunscreen Foundation Cosmetics",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.6,
    reviewCount: 73,
    inStock: false,
    tags: ["sale", "new", "beauty", "accessory"],
    isNew: true
  },
  {
    id: 17,
    category: "home",
    brand: "dino",
    img: "/images1/imag22.png",
    discount: "40%",
    title: "Dino Chair by Thomas Alken",
    price: "$150",
    originalPrice: "$250",
    rating: 4.1,
    reviewCount: 29,
    inStock: true,
    tags: ["sale", "new", "home"],
    isNew: true
  },
  {
    id: 18,
    category: "clothing",
    brand: "prada",
    img: "/images1/imag26.png",
    discount: "50%",
    title: "PRADA Saffiano leather shoulder bag",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    tags: ["sale", "new", "bestseller", "clothing", "accessory"],
    isNew: true
  },
  {
    id: 19,
    category: "electronics",
    brand: "moonlight",
    img: "/images1/imag28.png",
    discount: "50%",
    title: "Moonlight Speaker", 
    price: "$700",
    originalPrice: "$1400",
    rating: 4.3,
    reviewCount: 41,
    inStock: true,
    tags: ["sale", "new", "electronics", "accessory"],
    isNew: true
  },
  {
    id: 20,
    category: "electronics",
    brand: "oppo",
    img: "/images1/imag31.png",
    discount: "50%",
    title: "OPPO ECOUTEUR WIRELESS W11",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.5,
    reviewCount: 68,
    inStock: true,
    tags: ["sale", "new", "electronics", "accessory"],
    isNew: true
  },
  {
    id: 21,
    category: "electronics", 
    brand: "dyson",
    img: "/images1/imag25.png",
    discount: "",
    title: "Accessoires De Sèche-cheveux Dyson",
    price: "$900",
    originalPrice: null,
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    tags: ["new", "bestseller", "electronics", "accessory"],
    isNew: true
  },
  {
    id: 22,
    category: "beauty",
    brand: "onoma",
    img: "/images1/imag27.png",
    discount: "50%",
    title: "onoma® Skincare brand",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.4,
    reviewCount: 55,
    inStock: true,
    tags: ["sale", "new", "beauty", "accessory"],
    isNew: true
  },
  {
    id: 23,
    category: "beauty",
    brand: "rated",
    img: "/images1/imag29.png",
    discount: "50%",
    title: "Rated Green Real Tamanu Shampoo",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.2,
    reviewCount: 33,
    inStock: true,
    tags: ["sale", "new", "beauty", "accessory"],
    isNew: true
  },
  {
    id: 24,
    category: "home",
    brand: "nordic",
    img: "/images1/imag32.png",
    discount: "50%",
    title: "Nordic Simple Design Sofa",
    price: "$700",
    originalPrice: "$1400",
    rating: 4.6,
    reviewCount: 79,
    inStock: true,
    tags: ["sale", "new", "home"],
    isNew: true
  }
];

export const products = [...featuredProducts, ...newProducts];